Header
0ro/technormart pull request #1
Opened 2018-07-21 13:33 UTC by kleymenova

Шапка без эвентов

2018-07-21 14:27 UTC, 0ro requested changes

2018-07-21 14:27 UTC, 0ro commented on index.html
> +  <script>document.write('<script src="http://' + (location.host || 'localhost').split(':')[0] + ':35729/livereload.js?snipver=1"></' + 'script>')</script>
Все что нужно тебе для разработки не должно попадать в код проекта

2018-07-21 14:27 UTC, 0ro commented on css/style.css
> +  min-width: 100%;
Шапка у тебя получилась резиновой (на всю ширину), согласно макету она равна 940px. При том, что темно синий фон позади шапки должен быть на всю ширину

2018-07-21 14:27 UTC, 0ro commented on css/style.css
> +  position: absolute;
Зачем здесь понадобился absolute?

2018-07-21 14:27 UTC, 0ro commented on css/style.css
> +  height: 42px;
Фиксирование высоты это всегда плохо, нужно максимально этого избегать, и применять там, где без этого не обойтись. Здесь из-за того, что ты задала position: absolute блок схлопнулся, и потерял возможность изменения высоты по содержимому. И поэтому тебе пришлось указывать высоту.

2018-07-21 14:27 UTC, 0ro commented on css/style.css
> +  height: 42px;
Если без этого не обойтись, то лучше найти компромисс между min-height, max-height

2018-07-21 14:27 UTC, 0ro commented on css/style.css
> +  line-height: 41px;
Line-height в данном случае лучше задавать у конктретных элементов, чем у родителя

2018-07-21 14:27 UTC, 0ro commented on css/style.css
> +  position: absolute;
Можно обойтись без absolute. Он здесь не нужен. Верстка с использованием absolute - признак плохой верстки

2018-07-21 14:27 UTC, 0ro commented on css/style.css
> +  width: 222px;
Задавать высоту и ширину здесь (у родительского элемента блока logo) не совсем круто. Эта высота и ширина, должна быть у самого блока logo. Если сейчас скопировать элемент с классом logo он сломается. Высоту и ширину в кнопках лучше делать за счет padding.

2018-07-21 14:27 UTC, 0ro commented on img/icon-search
> +</svg>
Эти изображения не были использованы?

2018-07-21 14:27 UTC, 0ro commented on index.html
> +    <div class="header__item header__item_left">
Ты пропустила где то закрывающий тэг </div> Потому что у тебя внутри header__item остальные header__item. А они по всей видимости должны быть на одном уровне вложенности

2018-07-21 14:27 UTC, 0ro commented on index.html
> +        <div class="logo">
Logo должно быть ссылкой. Или внутри блока logo толжа быть ссылка на корневую страницу сайта.

2018-07-21 14:27 UTC, 0ro commented on index.html
> +        <span class="search">
Блок search должен быть input. Люди должны иметь возможность туда что то вводить.

2018-07-21 14:27 UTC, 0ro commented on index.html
> +          <i class="fas fa-search icon__awsome icon__awsome_grey"></i>
табуляцию добавь перед тэгом i, чтобы была видна вложенность

2018-07-21 14:27 UTC, 0ro commented on index.html
> +            <i class="fas fa-bookmark icon__awsome icon__awsome_grey"></i></span>
Закрывающий span нужно отбить вниз, и табуляцию добавить

2018-07-21 14:27 UTC, 0ro commented on index.html
> +            Закладки: 0
Нолик нужно обернуть в span хотя бы. И все элементы которые будут возможно изменяться нужно оборачивать в отдельный тэг, чтобы потом на js можно было легко с ними манипулировать (обращаться к ним, заменять текст внутри них)

2018-07-21 14:27 UTC, 0ro commented on index.html
> +      <!-- backet -->
basket

2018-07-21 14:27 UTC, 0ro commented on index.html
> +  <div class="header">
Давай все-таки верстать на HTML5 там где это возможно.

2018-07-21 14:27 UTC, 0ro commented on css/style.css
> +  position: absolute;
Везде убрать absolute. За это бьют по рукам

2018-07-21 14:27 UTC, 0ro commented on css/style.css
> +  width: 149px;
Ширину и высоту паддингами делай у кнопок

2018-07-21 14:27 UTC, 0ro commented on css/style.css
> +  width: 149px;
или в данном случае круто должно срабатывать height: 100%

2018-07-21 14:27 UTC, 0ro commented on css/style.css
> +  float: right;
Попробуй без этого. Изучи что делает display: inline-block. Здесь всю шапку круто сделать с его помощью

2018-07-21 14:27 UTC, 0ro commented on index.html
> +      <div class="header__item header__item-logo">
назови просто header__logo

2018-07-21 14:27 UTC, 0ro commented on index.html
> +      <div class="header__item header__item_right">
Очень сильно полюбила слово item. Старайся давать более осмысленные названия блокам и их элементам.

2018-07-21 16:45 UTC, kleymenova commented on index.html
> +  <script>document.write('<script src="http://' + (location.host || 'localhost').split(':')[0] + ':35729/livereload.js?snipver=1"></' + 'script>')</script>
а куда этот код вставлять?

2018-07-21 16:47 UTC, 0ro commented on index.html
> +  <script>document.write('<script src="http://' + (location.host || 'localhost').split(':')[0] + ':35729/livereload.js?snipver=1"></' + 'script>')</script>
Перед коммитом нужно удалять. Это твои личные инструменты, это не должно попадать в проект

2018-07-23 13:02 UTC, kleymenova commented on css/style.css
> +  position: absolute;
за relative не бьют?

2018-07-23 13:11 UTC, 0ro commented on css/style.css
> +  position: absolute;
нет, за relative не бьют) но за позиционирование с помощью relative бьют. Если ты помнишь, я рассказывал, что relative у родителя, заставляет дочерний элемент, у которого postion: absolute отсчитывать свои координаты от родителя, если ни у одного из родителей нет relative, то элемент будет координирован по левому верхнему углу окна браузера. Поэтому relative используется в связке с absolute. А absolute используется там, где нужно чтобы элемент "выпадал из потока документа", т.е. как бы был сверху всего и при этом все остальные объекты его не замечали и не перестраивались в зависимости от него. Это разные выпадающие меню, модальные окна (попапы), выезжающие подсказки, иконки на кнопках и в полях ввода

2018-07-26 12:47 UTC, 0ro requested changes

2018-07-26 12:47 UTC, 0ro commented on css/style.css
> +.top {
Шапка в этом макете - это весь верхний блок + блок с инфо  и контактами + меню. Логично было бы назвать весь блок .header, а внутри него уже сделать .header__top, .header__middle, .header__bottom или .header__panel, .header__info, .header__menu. Называть весь блок top - плохо. Такими короткими классами, которые совпадают по названию со свойствами CSS пользуются для фиксирования каких то значений свойств. Например: 
.top {
  top: 5px;
}
И потом в html всем блокам где нужна этот top добавлять класс top. Видел в своей практике еще такие классы padding-3, margin-top-10, border-radius-3. Я бы не сказал, что это хорошая практика, но кто то так делает и ему удобно.

2018-07-26 12:47 UTC, 0ro commented on css/style.css
> +* {
За это бьют по рукам. Нельзя так глобально переписывать все стили. Лучше руками каждому где это нужно прописать padding и margin. Получается у тебя все что ты не добавишь получит эти свойства. Для браузера - это не самая трудоемкая операция, но ему нужно построить HTML дерево, потом CSS дерево, а он будет тратить в пустую свои ресурсы на твои звездочки.

2018-07-26 12:47 UTC, 0ro commented on css/style.css
> +  text-align: center;
text-align это наследуемое свойство. Т.к. ты его здесь задала, все дочерние элементы body (а это все элементы), которые умеют понимать это свойство будут выровнены по центру и тебе придется у каждого блока где это нужно ставить text-align: left. Поэтому определи это свойство менее глобально.

2018-07-26 12:47 UTC, 0ro commented on css/style.css
> +  width: 960px;
940px

2018-07-26 12:47 UTC, 0ro commented on css/style.css
> +  margin-left: 11px;
из за этого у тебя здесь такое магическое число, потому что пытаешься попасть в pixel perfect, но при этом не сделала нужной ширину шапки. Нужно стараться избегать всех магических чисел если только нет другого выхода.

2018-07-26 12:47 UTC, 0ro commented on css/style.css
> +  padding: 8px 57px 8px 57px;
padding: 8px 57px - если можно написать короче - пиши

2018-07-26 12:47 UTC, 0ro commented on css/style.css
> +  float: left;
float: left/right и display: inline-block у .header__item - это жгучая смесь. Выбери что то одно

2018-07-26 12:47 UTC, 0ro commented on css/style.css
> +  font-family: 'Cuprum', sans-serif;
В body

2018-07-26 12:47 UTC, 0ro commented on css/style.css
> +  color:#FFFFFF !important;
!important никогда не надо использовать. Если это из за того, что у тебя текст не белый. То он не белый, потому что его нужно менять не так, а так http://htmlbook.ru/blog/tsvet-zameshchayushchego-teksta
Его менять не будем, пусть будет серый как сейчас

2018-07-26 12:47 UTC, 0ro commented on index.html
> +        <div class="icon_search">
Ты в icon_search обернула и поле - не надо так

2018-07-26 12:47 UTC, 0ro commented on css/style.css
> +  padding: 12px 26px 12px 23px;
padding: 12px 26px; Не нужно делать pixel-perfect до такой степени - это извращение.

2018-07-26 12:47 UTC, 0ro commented on css/style.css
> +.logo {
Не забывай про эффекты по наведению, которые описаны в styleguide.psd

2018-07-30 12:58 UTC, alenanagval reviewed
а его как-то подключить надо? я всегда думала что это и есть HTML5

2018-07-30 12:58 UTC, alenanagval commented on css/style.css
> +  width: 222px;
Да, это я помню! просто там еще один лого, у которого другая высота, но посмотрела, вроде не критично, 
исправила

2018-07-30 12:58 UTC, alenanagval commented on index.html
> +  <div class="header">
а его как-то подключить надо? я всегда думала что это и есть HTML5

2018-07-30 12:58 UTC, alenanagval commented on css/style.css
> +  margin-left: 11px;
про магические числа не поняла, это @@ -29,8 +29,7... это они? больше вроде нигде не вылазят они

2018-07-30 12:58 UTC, alenanagval commented on css/style.css
> +.logo {
а можно на чистом css все это написать, например при наведении на один элемент, меняется другой?или js надо подключать? пока эффекты сырые

2018-07-30 12:58 UTC, kleymenova commented on index.html
> +  <div class="header">
а его как-то подключить надо? я всегда думала что это и есть HTML5

2018-07-30 13:03 UTC, 0ro commented on index.html
> +  <div class="header">
HTML5 - это спецификация, которая включает в себя и все предыдующие для их поддержки. Под фразой верстать по HTML5 всегда понимают то, что нужно верстать с использованием возможностей, которые появились в ней, а именно новые тэги, которые более семантичны чем просто div. Вот почитай https://ru.wikipedia.org/wiki/HTML5#%D0%9E%D1%82%D0%BB%D0%B8%D1%87%D0%B8%D1%8F_HTML5_%D0%BE%D1%82_HTML4.01_%D0%B8_XHTML1.0

2018-07-30 13:19 UTC, alenanagval reviewed
про магические числа не поняла, это @@ -29,8 +29,7... это они? больше вроде нигде не вылазят они

2018-08-01 12:42 UTC, 0ro requested changes

2018-08-01 12:42 UTC, 0ro commented on css/style.css
> +  padding-left: 13px;
Здесь больше подходит margin

2018-08-01 12:42 UTC, 0ro commented on css/style.css
> +}
Смотри, ты добавила новый класс для инпутов, .form-control. В дальнейшем удобно будет для остальных инпутов использовать этот же класс. Поэтому необходимо часть относящуюся только к поиску вынести отсюда, а оставить только общую для всех инпутов (font-family, font-size, border, padding: 11px 6px). Вынести можно добавив вложенность для классов. Например: .header__search .form-control {} и добавить стили относящиеся к нему, или добавить модификатор для form-control_search и добавить этот класс к этому полю.

2018-08-01 12:42 UTC, 0ro commented on css/style.css
> +  margin: 0 -16px 0 -4px;
ты поняла почему тебе здесь понадобилось добавить отрицательный margin?

2018-08-01 14:45 UTC, kleymenova commented on css/style.css
> +  margin: 0 -16px 0 -4px;
у меня он тут потому что блок не прилипал к смежным блокам)

2018-08-01 14:47 UTC, 0ro commented on css/style.css
> +  margin: 0 -16px 0 -4px;
Вот здесь почитай про эти загадочные отступы
http://css-live.ru/articles/zagadochnye-otstupy-mezhdu-inlajn-blokami.html

2018-08-01 14:50 UTC, kleymenova commented on css/style.css
> +  margin: 0 -16px 0 -4px;
ага, тут как раз и читала, но там вроде такой вариант тоже есть, с отрицательным марджином, так это правильно?

2018-08-01 14:52 UTC, 0ro commented on css/style.css
> +  margin: 0 -16px 0 -4px;
Конечно правильно, главное чтобы ты понимала, что это из-за display: inline-block, точнее из-за его инлайновой природы. Только по этому его не используют в сетках, а используют там где нужно быстро поставить блоки рядом друг с другом не заморачиваясь о точной их позиции.

2018-08-01 14:53 UTC, 0ro commented on css/style.css
> +  margin: 0 -16px 0 -4px;
Здесь мы оставим display: inline-block, нужно было чтобы ты наступила на это

2018-08-02 09:28 UTC, 0ro requested changes

2018-08-02 09:28 UTC, 0ro commented on css/style.css
> +  margin-left: -20px;
Взаимоуничтожающие свойства. Убери их, и иконку смести влево

2018-08-02 09:28 UTC, 0ro commented on css/style.css
> +.form-control:focus+.icon__awsome_grey-search {
Вот это тоже нужно вынести для .form-control_search

2018-08-02 09:28 UTC, 0ro commented on css/style.css
> +  display: flex;
Не нужно указывать display: flex для дочерних элементов, достаточно, только для .header__top. Убери здесь это свойство, верстка слегка сломается, но ее можно поправить присвоив ссылочным блокам logo и checkout display: block/inline-block

2018-08-02 09:28 UTC, 0ro commented on css/style.css
> +  display: flex;
вот крутая статья по флексбоксам https://css-tricks.com/snippets/css/a-guide-to-flexbox/. Если что то останется не понятным спрашивай

2018-08-02 18:50 UTC, alenanagval reviewed
а его как-то подключить надо? я всегда думала что это и есть HTML5

2018-08-02 18:50 UTC, kleymenova commented on css/style.css
> +  display: flex;
присвоила inline-block, сломалась сафари опять так же(

2018-08-02 18:52 UTC, 0ro commented on css/style.css
> +  display: flex;
Кому присваивала inline-block?

2018-08-21 17:02 UTC, 0ro requested changes

2018-08-21 17:02 UTC, 0ro commented on css/style.css
> +  padding-left: 45px;
Это свойство снеси в .form-control_search. И здесь добавь padding: 0, margin: 0, для того, чтобы избежать неожиданностей в разных браузерах

2018-08-21 17:02 UTC, 0ro commented on css/style.css
> +  max-height: 40px;
Это убрать

2018-08-21 17:02 UTC, 0ro commented on css/style.css
> +  line-height: 42px;
Это убрать

2018-08-21 17:02 UTC, 0ro commented on css/style.css
> +  min-height: 40px;
Это убери

2018-08-21 17:02 UTC, 0ro commented on css/style.css
> +  font-family: 'Cuprum', sans-serif;
Вроде писал уже, что нужно убрать

2018-08-22 05:27 UTC, 0ro approved these changes

2018-08-22 06:22 UTC, merged