Service
0ro/technormart pull request #11
Opened 2018-10-08 10:08 UTC by kleymenova

2018-10-08 10:34 UTC, 0ro requested changes

2018-10-08 10:34 UTC, 0ro commented on index.html
> +        <div class="services__content delivery services__delivery">
Что было не так в пердыдущей структуре, что пришлось заменить на эту? почему сейчас у одного html элемента есть два класса, относящиеся ка разным элементам? Почему не подошла структура:
```
.services__content
  .delivery
  .guarantee
  .credit
```

2018-10-08 10:34 UTC, 0ro commented on css/style.css
> +[type="radio"] {
почему не БЭМ?

2018-10-08 10:34 UTC, 0ro commented on css/style.css
> +.radio-btns label {
почему не БЭМ?

2018-10-08 10:34 UTC, 0ro commented on css/style.css
> +  margin: 63px 0 0 66px;
Почему margin, а не padding?

2018-10-08 10:34 UTC, 0ro commented on css/style.css
> +  /*box-shadow: inset 0 0 10px 5px rgba(221, 221, 221, 1);*/
Для чего здесь комментарий?

2018-10-08 10:34 UTC, 0ro commented on css/style.css
> +  line-height: 1.7em;
Для чего здесь em?

2018-10-08 10:34 UTC, 0ro commented on css/style.css
> +  margin-top: 48px;
Я думаю, нужно сюда паддинг перенести из `.service__serv-desсription`, а ты?

2018-10-08 10:34 UTC, 0ro commented on css/style.css
> +  padding-bottom: 21px;
Почему здесь padding?

2018-10-08 10:34 UTC, 0ro commented on css/style.css
> +  line-height: 2em;
Почему здесь нужен em?

2018-10-08 14:10 UTC, alenanagval commented on css/style.css
> +  margin-top: 48px;
ага, зачем это я лишний селектор сделала

2018-10-08 14:10 UTC, alenanagval commented on css/style.css
> +  padding-bottom: 21px;
даже не знаю, что сказать в свое оправдание) поменяла на марджин

2018-10-08 14:10 UTC, alenanagval commented on css/style.css
> +  padding-bottom: 21px;
Иногда марджин не получается поставить, иначе код съезжает, но я потом с ним разбираюсь, а про марджин забываю

2018-10-08 14:10 UTC, alenanagval commented on css/style.css
> +  line-height: 2em;
я про него где-то вычитала, а как лучше, в пикселях?

2018-10-08 14:10 UTC, alenanagval commented on css/style.css
> +  /*box-shadow: inset 0 0 10px 5px rgba(221, 221, 221, 1);*/
забыла убрать

2018-10-08 14:10 UTC, alenanagval commented on css/style.css
> +[type="radio"] {
а как по БЭМ в этом случае?

2018-10-08 14:10 UTC, alenanagval commented on css/style.css
> +  margin: 63px 0 0 66px;
я думаю тут отступ от соседних элементов

2018-10-08 14:10 UTC, kleymenova commented on index.html
> +        <div class="services__content delivery services__delivery">
нужно было элементы .delivery .guarantee .credit объединить общим классом, но я придумала, как объединить некоторые стили, чтоб каждому не писать, и почему-то тильда у меня через родителя не хотела работать, сейчас переделала, все работает))

2018-10-08 14:13 UTC, 0ro commented on css/style.css
> +[type="radio"] {
`.radio`

2018-10-08 14:26 UTC, 0ro commented on css/style.css
> +  margin: 63px 0 0 66px;
по мне тут padding чистый. Вообще ты должна привыкнуть что почти любой блок в котором есть содержимое должен иметь padding какой-то. Я не знаю как это еще объяснить. Вижу, что у тебя с этим проблемы

2018-10-08 14:35 UTC, 0ro commented on css/style.css
> +  line-height: 2em;
Вот здесь хорошо написано когда что лучше https://learn.javascript.ru/css-units

2018-10-09 11:32 UTC, 0ro approved these changes

2018-10-09 11:36 UTC, merged