About
0ro/technormart pull request #12
Opened 2018-10-09 14:10 UTC by kleymenova

2018-10-11 10:37 UTC, 0ro requested changes

2018-10-11 10:37 UTC, 0ro commented on index.html
> +      <div class="company about__company">
Заметил, что ты прям сделала правило, что каждый блок должен иметь класс, который формируется по такому принципу `company about__company`. Не обязательно нужно делать так. Так получается бездушно. Блок about имеет левый и правый элемент и нужно так и называть - about__left, alout__right. Старайся уменьшать связность

2018-10-11 10:37 UTC, 0ro commented on index.html
> +          <img src="img/map-popup.png" alt="Карта Техномарт" class="map-popup hide">
Здесь карта должна быть настоящая из google

2018-10-11 10:37 UTC, 0ro commented on index.html
> +          <img src="img/map-popup.png" alt="Карта Техномарт" class="map-popup hide">
Сам попап нужно будет спроектировать как отдельный блок. В нем должна быть кнопка закрытия и элемент, где будет храниться содержимое. Плюс еще нужно сделать затемняющий фон. На который тоже если нажмут попап должен будет закрываться. Мы должны будет иметь возможность легко изменять содержимое попапа.

2018-10-11 10:47 UTC, kleymenova commented on index.html
> +      <div class="company about__company">
тоже предстоит почувствовать тонкую грань БЭМа) а что значит уменьшить связность?

2018-10-11 10:50 UTC, 0ro commented on index.html
> +      <div class="company about__company">
Уменьшить зависимость. У тебя сейчас блок .about зависит от того, что в нем находится. Если мы вдруг решим поменять местами блок company и map. То придется менять названия классов about__company или стили его.

2018-10-12 08:26 UTC, 0ro requested changes

2018-10-12 08:26 UTC, 0ro commented on index.html
> +        <section class="map-popup about__map-popup">
У нас должен быть блок popup, в котором не обязательно будет карта. Там может быть сообщение об успехе какого либо события, авторизация, акция и пр. Сейчас получается, что этот popup только про карту. Popup должен лежать в общедоступном месте, обычно в самом низу, перед закрывающим тэгом body.

2018-10-12 08:26 UTC, 0ro commented on index.html
> +          <li class="about__list_item">Деловые линии</li>
Модификатор?

2018-10-12 08:26 UTC, 0ro commented on index.html
> +        <nav class="services-nav services__services-nav">
Здесь nav не подходит. Он применяется в блоках со ссылками

2018-10-12 08:26 UTC, 0ro commented on index.html
> +    <section class="popular content__popular">
Не лепи section где попало. http://htmlbook.ru/html/section

2018-10-12 09:22 UTC, kleymenova commented on index.html
> +    <section class="popular content__popular">
Денис, как ты думаешь, заголовки скрытые нужно для section? или пусть так остается?

2018-10-12 09:24 UTC, 0ro commented on index.html
> +    <section class="popular content__popular">
Что имеешь ввиду под скрытые заголовки?

2018-10-12 12:12 UTC, 0ro requested changes

2018-10-12 12:12 UTC, 0ro commented on index.html
> +        <a href="#" class="btn btn_red btn_border-rad uppercase about__btn">
Нужен еще блок, с картой. Который будет по умолчанию скрыт. На js мы будем по нажатию на превью, копировать этот блок в попап и отображать попап. Попап тоже должен быть по умолчанию скрыт

2018-10-12 12:12 UTC, 0ro commented on index.html
> +      <div class="popup__fond">
Почему fond?

2018-10-13 07:50 UTC, kleymenova commented on index.html
> +      <div class="popup__fond">
гугл переводчик сказал, что это тоже фон) background-длинно слишком.

2018-10-13 07:50 UTC, kleymenova commented on index.html
> +        <a href="#" class="btn btn_red btn_border-rad uppercase about__btn">
а вот эту маленькую картинку с картой тогда в какой блок поставить? я думала что блок с картой и картинка в нем-одно и то же, но она не скрыта

2018-10-13 07:55 UTC, 0ro commented on index.html
> +      <div class="popup__fond">
Этот элемент для хранения содержимого, поэтому здесь лучше подойдёт content

2018-10-13 15:31 UTC, 0ro commented on index.html
> +        <a href="#" class="btn btn_red btn_border-rad uppercase about__btn">
Здесь и должна остаться. Но нужен ещё блок с Google map. Изучи как добавлять карту на сайт и добавь

2018-10-13 17:19 UTC, 0ro approved these changes

2018-10-13 17:20 UTC, merged