banner html
0ro/technormart pull request #2
Opened 2018-08-22 10:52 UTC by kleymenova

2018-08-22 10:56 UTC, 0ro requested changes

2018-08-22 10:56 UTC, 0ro commented on index.html
> +  <!-- banner -->
Это все таки не баннер. Баннер - это нечто коммерческое, рекламное, которое, как правило представлено изображением. Здесь это название ни к чему. Плюс даже если ты верстаещь баннер, называть его классом banner не стоит, потому что есть всякие AdBlock (блокировщики рекламы), которые реагируют блоки с таким названием и убирают их из верстки

2018-08-22 10:56 UTC, 0ro commented on index.html
> +  <!-- banner -->
У нас это шапка, и давай раз мы верхний называли header__top, то этот блок нужно разместить внутри .header, и назвать .header__middle например

2018-08-23 08:24 UTC, 0ro requested changes

2018-08-23 08:24 UTC, 0ro commented on index.html
> +      <div class="container container__display_flex">
Если по БЭМ, то container_display_flex - названиеблока_модификация_значение
Здесь возможно, т.к. у тебя в этом свойстве в стилях только display: flex, то класс можно назвать flex, и потом подмешивать его везде где нужен именно flex. Помнишь я говорил о таком стиле написания классов, когда они соответствуют названиям свойств?

2018-08-23 08:24 UTC, 0ro commented on index.html
> +              +7 (812) 555-05-55
Лучше не оставлять вот так голый текст. Когда нибудь обязательно понадобится его динамически менять, и тебе придется его во что-то обернуть, чтобы к нему обратиться через js.

2018-08-23 08:24 UTC, 0ro commented on index.html
> +            <i class="fas fa-phone contacts__phone-icon">
У меня есть такое личное правило, если я начинаю вставлять в элемент элемент (а здесь это и происходит, ты вставляешь в элемент phone блока contacts еще элемент, такого в БЭМ нет), то значит я делаю что то не так со структурой. Ты и комментарий phone написала, так и сделай целый блок phone, у которого будет phone__icon и phone__value например

2018-08-23 08:24 UTC, 0ro commented on index.html
> +            <i class="fas fa-phone contacts__phone-icon">
Почитай про БЭМ https://ru.bem.info/methodology/quick-start/

2018-08-23 08:24 UTC, 0ro commented on index.html
> +          <div class="contacts__address">
Назови блок address, а к нему примиксуй contacts__address для позиционирования

2018-08-23 08:24 UTC, 0ro commented on index.html
> +          <a class="entrance__sign-in button_white button_white-sign-in" href="#">
Посмотри с названиями классов как сделано в bootstrap. Для всего общего в кнопках у них есть класс .btn, для модицикаций, можно добавить несколько состояний, btn_default, btn_info, btn_success, btn_danger. Если у кнопки есть иконка внутри то добавить модификатор btn_icon, и там уже отступать место под иконку или еще что то, если есть скругления, то модификатор btn_rad. Эти классы должны быть универсальными и не привязаны к контексту какой то отдельной кнопки. Для уточнения контекста миксуй (entrance__sign-in в этом случае)

2018-08-23 10:34 UTC, kleymenova commented on index.html
> +          <div class="contacts__address">
address contacts__address? или address родитель а contacts__address дите?

2018-08-23 10:34 UTC, kleymenova commented on index.html
> +            <i class="fas fa-phone contacts__phone-icon">
а contacts оборачиваем еще в родителя для позиционирования?

2018-08-23 10:36 UTC, 0ro commented on index.html
> +          <div class="contacts__address">
address contacts__address чтобы лишнию вложенность не городить, но можно и так и так

2018-08-23 10:40 UTC, 0ro commented on index.html
> +            <i class="fas fa-phone contacts__phone-icon">
Можешь примиксовать к нему header__contacts. Или в header__middle полjжить блок и придумать какое то название для этих трех блоков (descirption, contacts, button-group) и сделать их элементами его.

2018-08-23 10:47 UTC, kleymenova commented on index.html
> +            <i class="fas fa-phone contacts__phone-icon">
а есть в этом обертывании смысл, какие-то плюсы оно потом даст по сравнению с присваиванием доп.класса?

2018-08-23 11:21 UTC, 0ro commented on index.html
> +            <i class="fas fa-phone contacts__phone-icon">
Кроме того, что тебе визуально более виден блок нет. Это по вкусу. Мне больше нравится подмешивать

2018-08-28 07:07 UTC, 0ro approved these changes

2018-08-28 07:07 UTC, merged