content structure
0ro/technormart pull request #6
Opened 2018-09-02 18:06 UTC by kleymenova

2018-09-03 06:22 UTC, 0ro requested changes

2018-09-03 06:22 UTC, 0ro commented on index.html
> +    <div class="card content__card content__card_first content__card_new">
Для чего нужны модификаторы с порядковым номером здесь?

2018-09-03 06:22 UTC, 0ro commented on index.html
> +      <a class="card__btn card__btn_first" href="#">
Сделай это отдельным блоком btn, у которого за счет модификатора задашь нужное отображение, uppercase и прозрачность.

2018-09-03 06:22 UTC, 0ro commented on index.html
> +  <div class="content container">
Content это блок, в котором будут все блоки до футера. Блок, который мы сейчас делаем нуждается в другом названии. Плюс ко всему лучше делать сетку прямо сейчас.

2018-09-04 07:24 UTC, alenanagval commented on index.html
> +    <div class="card content__card content__card_first content__card_new">
их не нужно идентифицировать, каждый блок?

2018-09-04 07:27 UTC, 0ro commented on index.html
> +    <div class="card content__card content__card_first content__card_new">
А для чего?

2018-09-04 07:31 UTC, kleymenova commented on index.html
> +  <div class="content container">
через свойство display: grid ?

2018-09-04 10:54 UTC, 0ro requested changes

2018-09-04 10:54 UTC, 0ro commented on index.html
> +  <div class="main container">
Я ведь не просил переименовывать блок content. Тебе нужно чтобы у тебя была такая структура:
header
content
footer
Шапку мы уже сделали, теперь перешли на блок content. В этом блоке куча остальных. Этот блок можно назвать блок offers. Т.е. должно получиться так:
header
content
    offers
    ...
footer

2018-09-05 06:35 UTC, 0ro requested changes

2018-09-05 06:35 UTC, 0ro commented on index.html
> +      <div class="card offers__card offers__card_new">
new - это ведь модификатор card

2018-09-05 06:35 UTC, 0ro commented on index.html
> +      <div class="card offers__card offers__card_new">
И как ты будешь задавать цвета для каждой из карточек?

2018-09-05 06:35 UTC, 0ro commented on index.html
> +      <div class="card offers__card offers__card_new">
Можешь делать без сетки если для тебя это пока сложно

2018-09-06 08:03 UTC, 0ro approved these changes

2018-09-06 08:03 UTC, merged