Content
0ro/technormart pull request #7
Opened 2018-09-12 11:16 UTC by kleymenova

2018-09-12 12:14 UTC, 0ro requested changes

2018-09-12 12:14 UTC, 0ro commented on index.html
>          <div class="slider__title">
Тебе на данный момент нужно реализовать в слайдере такую структуру:
```
slider
  slide
    ...содержимое слайда
  slide
    ...содержимое второго слайда

2018-09-12 12:14 UTC, 0ro commented on index.html
>          <div class="slider__title">
Стрелки делать не нужно. За тебя их добавит js. Вот отличный плагин, которым все пользуются
http://kenwheeler.github.io/slick/

2018-09-12 12:14 UTC, 0ro commented on index.html
> +        <div class="card offers__card card_orange card_new inline-block">
Я попробовал удалить все кроме card, для того чтобы проверить все ли ок. И у card пропал фон. В блоке должны быть минимально необходимые стили для нормального отображения. Т.е. даже без модификаторов он должен хорошо смотреться. Мы по моему это обсуждали.

2018-09-12 12:14 UTC, 0ro commented on index.html
> +      <div class="row content__row">
Давай попробуем сделать вообще без сеток и их имитаций. Сделай такую структуру:
```
offers
  card
  card
  card
  slider
  card
  card
```
И пробуй сделать все чище и с использованием float: left. И почитай про clearfix и зачем он нужен

2018-09-12 12:14 UTC, 0ro commented on css/style.css
> +  padding: 24px 0 0 19px;
Все таки margin или padding?

2018-09-12 12:14 UTC, 0ro commented on css/style.css
> +  width: 138px;
Ширину кнопки лучше через padding сделать

2018-09-12 12:14 UTC, 0ro commented on index.html
>    <!-- card 1 -->
Вижу ты полюбила комментировать, но хочу тебя убедить, что в разметке лучше любых комментариев за тебя говорит чистая и понятная структура. И нет ничего хуже устаревших комментариев, они только сбивают с толку. Если хочешь комментировать, то лучше это делать когда все все закончишь. Тогда это нужно будет сделать один раз. Сейчас во время разработки ты только тратишь время на поддержание их актуальности.

2018-09-12 12:15 UTC, 0ro commented on index.html
>          <div class="slider__title">
Попытайся "прикрутить" это плагин к нашему слайдеру

2018-09-12 12:25 UTC, alenanagval commented on css/style.css
> +}
а new я нормально сделала?

2018-09-12 12:25 UTC, alenanagval commented on index.html
> +          <svg xmlns="http://www.w3.org/2000/svg" width="75" height="61" viewBox="0 0 75 61" class="card__icon"><g fill="#FFF"><path d="M5.039 58.949S5.039 61 6.907 61h27.02s2.001-.184 2.001-1.984V47
то что я через svg иконки вставила это норм? и позиционировать их только через position:absolute получилось, иначе они не влезали, или лучше вырезать и вставить как бэкграунд имейдж?

2018-09-12 17:39 UTC, 0ro commented on css/style.css
> +}
На этом этапе я бы оставил так, но этот же модификатор, круче сделать в html отдельным блоком, чтобы текст можно было менять

2018-09-12 17:39 UTC, 0ro commented on css/style.css
> +}
Решил это не писать, потому что не принципиально сейчас это

2018-09-12 17:40 UTC, 0ro commented on index.html
> +          <svg xmlns="http://www.w3.org/2000/svg" width="75" height="61" viewBox="0 0 75 61" class="card__icon"><g fill="#FFF"><path d="M5.039 58.949S5.039 61 6.907 61h27.02s2.001-.184 2.001-1.984V47
Можно и так и так

2018-09-12 17:41 UTC, 0ro commented on index.html
> +          <svg xmlns="http://www.w3.org/2000/svg" width="75" height="61" viewBox="0 0 75 61" class="card__icon"><g fill="#FFF"><path d="M5.039 58.949S5.039 61 6.907 61h27.02s2.001-.184 2.001-1.984V47
Но я бы делал с background

2018-09-18 10:20 UTC, alenanagval commented on css/style.css
> +  width: 138px;
тут ширина кнопки конкретной величиной задана, потому что в макете кнопки одинаковые по размеру, а если делать через паддинг, за счет того, что разный текст на них, они будут разные

2018-09-18 10:20 UTC, alenanagval commented on index.html
>    <!-- card 1 -->
с комментами удобно! особенно эти карточки 1,2,3...

2018-09-18 10:20 UTC, alenanagval commented on slick/config.rb
> +css_dir = "."
это сюда попало до того, как ты сказал что не надо)))

2018-09-18 10:20 UTC, alenanagval commented on slick/config.rb
> +css_dir = "."
всм slick

2018-09-18 11:52 UTC, 0ro requested changes

2018-09-18 11:52 UTC, 0ro commented on css/style.css
> +  width: 138px;
Это макет все таки, и в некоторых вещах лучше следовать тому, как принято делать в css

2018-09-18 11:52 UTC, 0ro commented on slick/config.rb
> +css_dir = "."
ок, удали эту папку тогда и закоммить

2018-09-18 11:52 UTC, 0ro commented on slick/config.rb
> +css_dir = "."
Плюс ко всему я не вижу файла .gitignore. Разберись с ним. Иначе перед каждым пушем, придется удалять node_modules, а потом снова npm install ранить.

2018-09-18 11:52 UTC, 0ro commented on js/main.js
> +$(document).ready(() => {
Вместо `() => ` напиши `function()`. Т.к. function arrow - это новый синтаксис и он не поддерживается на 100% всеми браузерами.

2018-09-18 11:52 UTC, 0ro commented on index.html
> +        <svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" width="78" height="63" viewBox="0 0 78 63" class="card__icon"><g fill="#FFF"><circle cx="25.983" cy="55.5" r
Не в качестве замечания, но тебе для раздумий. Как считаешь в чем недостаток и преимущество такого варианта добавления svg иконок? Какие есть еще варианты? Погугли

2018-09-18 11:52 UTC, 0ro commented on css/style.css
> +.content__offers:after {
Будет удобно если ты создашь класс clearfix и будешь потом миксовать его тем блокам, где нужно пофиксить схлопывание от float. Вот этот ниже код для ie8 и выше
```
.clearfix:after {
  content: "";
  display: table;
  clear: both;
}
```

2018-09-18 11:52 UTC, 0ro commented on css/style.css
> +/*------HAVBAR------*/
Navbar

2018-09-18 11:52 UTC, 0ro commented on index.html
> +        <div class="slider_1">
в чем необходимость такого названия блока? Просто `slide` назови. Если это модификатор, то он просто не может быть без блока

2018-09-18 17:54 UTC, 0ro requested changes

2018-09-18 17:54 UTC, 0ro commented on css/style.css
> +.slider__indicator {
Извини, что сразу не заметил этот блок. Его нужно убрать тебе и использовать точки, которые есть в slick. Посмотри как их добавить в документации. И стилизуй по макету. А то этот вариант очень некрасиво смотрится. Тебя должно было передернуть когда добавляла эти большие марджины и придти в голову, что ты делаешь, что то не так.

2018-09-18 17:54 UTC, 0ro commented on package.json
> +    "vue-slick": "^1.1.13"
вот это зачем здесь? Если он не нужен нужно выполнить удаление. `npm uninstall vue-slick`

2018-09-18 17:54 UTC, 0ro commented on .gitignore
> +slick/
Зачем здесь игнорить папку, которой быть не должно? И есть такое негласное правило, что все файлы должны заканчиваться пустой строкой, будь то css, html или вот такой gitignore

2018-09-19 09:25 UTC, alenanagval commented on .gitignore
> +slick/
пустой строкой в смысле нажать enter после последней строки файла?

2018-09-19 11:51 UTC, 0ro approved these changes

2018-09-19 11:51 UTC, merged