Popular
0ro/technormart pull request #9
Opened 2018-09-26 13:49 UTC by kleymenova

2018-09-27 07:37 UTC, 0ro requested changes

2018-09-27 07:37 UTC, 0ro commented on css/style.css
> +  position: absolute;
Не понял, в чем оправданность position absolute в данном случае? Элементы ведь идут один под другим. Возможно была проблема у тебя при наведении они съезжали вверх. Нужно передумать это.

2018-09-27 07:37 UTC, 0ro commented on css/style.css
> +  margin-right: 23px;
Ты все не можешь прочувствовать эту тонкую грань между padding и margin. В данном блоке это прям отчетливо видно, что popular-row имеет поля сверху и снизу 25px, а справа и слева 23px. И тогда не нужно будет всем элементам внутри добавлять эти марджины. Это ведь как в вордовском документе поля, нужно ограничить контент внутри, чтобы он не выходил за них. Так и здесь.

2018-09-27 07:37 UTC, 0ro commented on css/style.css
> +  margin-top: 24px;
Он здесь не нужен, старайся позиционирование делегировать либо элементам либо с помощью padding родительского блока/элемента

2018-09-27 07:37 UTC, 0ro commented on css/style.css
> +  border: 19px solid #fff;
Вместо #fff лучше использовать transparent

2018-09-27 07:37 UTC, 0ro commented on css/style.css
> +  border: 19px solid #fff;
И треугольник выпадает немного
![image](https://user-images.githubusercontent.com/7969190/46129875-93502a00-c240-11e8-95f0-8a024fc4610c.png)

2018-09-27 07:37 UTC, 0ro commented on index.html
> +              <a href="#" class="brand__img">
Два элемента с одинаковыми именами. Так нужно? Зачем?

2018-09-27 07:37 UTC, 0ro commented on index.html
> +                <img src="img/makita.png" alt="">
Заполни все alt. Это важно

2018-09-27 11:42 UTC, kleymenova commented on css/style.css
> +}
торчит немного теперь с обеих сторон равномерно, а то в других браузерах плохо смотрится

2018-09-27 11:45 UTC, 0ro commented on css/style.css
> +}
И как исправить это? Что в этом блоке изменяется от браузера к браузеру, что он меняет там высоту?

2018-09-27 11:57 UTC, 0ro requested changes

2018-09-27 11:57 UTC, 0ro commented on css/style.css
> +}
Неправильное решение. Ответь на вопрос

2018-09-28 06:48 UTC, 0ro requested changes

2018-09-28 06:48 UTC, 0ro commented on index.html
> +              <a href="#">
Получается, что только изображение имеет ссылку и только клик по нему вызовет переход на страницу бренда. Нужно сделать, чтобы весь блок был brand был ссылкой

2018-09-28 06:48 UTC, 0ro commented on index.html
> +              <img src="img/drill3000.png" alt="Перфоратор 3000" width="127" height="112">
Убери width и height отсюда, так нельзя делать

2018-09-28 06:48 UTC, 0ro commented on css/style.css
> +  width: 218px;
можно заменить на 100%

2018-09-28 14:00 UTC, 0ro approved these changes

2018-09-28 14:00 UTC, merged